[package]
name = "java"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.37"
serde = { version = "1.0.147", features = ["derive", "rc"] }
serde_json = "1.0.89"
once_cell = "1.16.0"

[target.'cfg(windows)'.dependencies]
winreg = "0"