version: 2.1

orbs:
  win: circleci/windows@5.0

executors:
  linux:
    docker:
      - image: cimg/go:1.19.0-node
    resource_class: medium
  website:
    docker:
      - image: cimg/go:1.19.0-node
    resource_class: medium
  mac:
    macos:
      xcode: "14.0.0"
    resource_class: medium
  macm1:
    macos:
      xcode: "14.0.0"
    resource_class: medium
  windows: win/default

jobs:
  build:
    parameters:
      os:
        type: string
    executor: <<parameters.os>>
    steps:
      - checkout
      # MACOS
      - when:
          condition:
            and:
              - equal: ["mac", <<parameters.os>>]
          steps:
            - run: |
                node -v
                go version
                sudo npm i -g pnpm
                pnpm i
                chmod -R a+x node_modules
                pnpm build-mac-x64
      # MACOS M1
      - when:
          condition:
            and:
              - equal: ["macm1", <<parameters.os>>]
          steps:
            - run: |
                node -v
                go version
                sudo npm i -g pnpm
                pnpm i
                chmod -R a+x node_modules
                pnpm build-mac-arm64
      # LINUX
      - when:
          condition:
            and:
              - equal: ["linux", <<parameters.os>>]
          steps:
            - run: |
                node -v
                go version
                sudo npm i -g pnpm
                pnpm i
                chmod -R a+x node_modules
                pnpm build-linux-x64
      # LINUX WEBSITE
      - when:
          condition:
            and:
              - equal: ["website", <<parameters.os>>]
          steps:
            - run: |
                node -v
                sudo npm i -g pnpm
                pnpm i
                chmod -R a+x node_modules
                pnpm build-web
  buildWin:
    working_directory: ./
    executor:
      name: win/default
      size: medium
    steps:
      - checkout
      - run:
          name: Install NVM
          shell: powershell.exe
          command: choco install nvm -y
      - run:
          name: Install Node 16.17.0
          shell: powershell.exe
          command: |
              nvm list
              nvm install 16.17.0
              nvm use 16.17.0
      - run:
          name: Verify Node Version
          shell: powershell.exe
          command: node --version
      - run: |
          $env:path += ";$env:appdata\npm"
          node -v
          go version
          npm i -g pnpm
          pnpm i
          pnpm build-win-x64
      - store_artifacts:
          path: ./apps/desktop/release
workflows:
  all-builds:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
          matrix:
            parameters:
              os: ["linux", "mac", "macm1", "website"]
      - buildWin:
          filters:
            branches:
              only:
                - master
                