version: 2.1
jobs:
  build:
    working_directory: ~/corbium
    docker:
      - image: cimg/node:18.6.0
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g yarn"
      # - restore_cache:
      #     key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Install dpkg and fakeroot
          command: |
            sudo apt-get update -y
            sudo apt-get install -y dpkg fakeroot

      # - save_cache:
      #     key: dependency-cache-{{ checksum "package.json" }}
      #     paths:
      #       - ./node_modules
      - run:
          name: Generate Builds
          command: yarn build

      - store_artifacts:
          path: ~/corbium/release
