[package]
name = "core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
config = "0"
lazy_static = "1"
napi = { version = "2", features = ["tokio_fs", "napi8", "tokio_rt", "async"] }
futures = "0"
anyhow = "1"
byteorder = "1"
reqwest = { version = "0", features = ["blocking", "json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0"
chrono = { version = "0", features = ["serde"] }
napi-derive = { version = "2", features = ["type-def"] }
tokio = "1"
murmurhash32 = { git = "https://github.com/gorilla-devs/murmurhash32.git" }
dotenv = "0"
rayon = "1"
jsonwebtoken = "7"
async-recursion = "1"
once_cell = "1"


[build-dependencies]
napi-build = "2"
