[package]
edition = "2021"
name = "core"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
async-recursion = "1"
base64 = "0"
byteorder = "1"
chrono = { version = "0", features = ["serde"] }
config = "0"
dotenv = "0"
futures = "0"
jsonwebtoken = "7"
lazy_static = "1"
murmurhash32 = { git = "https://github.com/gorilla-devs/murmurhash32.git" }
napi = { version = "2", features = ["tokio_fs", "napi8", "tokio_rt", "async"] }
napi-derive = { version = "2", features = ["type-def"] }
once_cell = "1"
rayon = "1"
reqwest = { version = "0", features = ["blocking", "json"] }
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
bincode = "1"
regex = "1"
directories = "4"


[target.'cfg(windows)'.dependencies]
winreg = "0"

[build-dependencies]
napi-build = "2"
